
import counsels_church from '../../public/counsels_for_church.jpg';
import counsels_diet from '../../public/counsels_on_diet.jpg';
import desire_ages from '../../public/desire_of_ages.jpg';
import heaven from '../../public/heaven.jpg';
import fundamentals from '../../public/fundamentals_education.jpg';
import patriarchs from '../../public/Patriachs.jpg';
import stewardship from '../../public/stewardship.jpg';
import controversy from '../../public/controversy.jpg';

export const booksList = [
    {src: controversy, title: "The Great Controversy", description:"Volume 5 of the Conflict of the Ages series carries the story of the controversy between God and Satan to its ultimate and glorious conclusion. Beginning with the destruction of Jerusalem and continuing through the persecutions of Christians in the Roman Empire, the apostasy of the Dark Ages, the shining light of the Reformation, and the worldwide religious awakening of the nineteenth century, this volume traces the conflict into the future, to the Second Coming of Jesus and the glories of the earth made new.", link:"https://m.egwwritings.org/en/book/133/info", read: "https://m.egwwritings.org/en/book/133", pdf: "https://media4.egwwritings.org/pdf/en_GC88.pdf", mp3: "https://media4.egwwritings.org/mp3/133/en_GC88.zip" },
    {src: counsels_church, title: "Counsels for the Church", description: "Counsels for the Church is a comprehensive selection of inspired materials from Ellen White that first appeared in books and periodicals during her lifetime. Grouped into sixty-six chapters, this counsel and instruction covers a wide range of topics. Because of space limitations, the compilers selected only the most essential and practical counsels on themes of significance and practical value to both the church and the individual. They are designed to draw Christians closer to God, giving them deeper insights into how to live daily in His love and grace.", link: "https://m.egwwritings.org/en/book/19/info", read: "https://m.egwwritings.org/en/book/19",  pdf: "https://media4.egwwritings.org/pdf/en_CCh.pdf", mp3: "https://media4.egwwritings.org/mp3/19/en_CCh.zip"},
    {src: counsels_diet, title: "Counsels on Diet and Foods", description: "Decades before many physiologists were concerned with the close relationship between diet and health, Ellen G. White in her writings clearly pointed out the connection between the food we eat and our physical and spiritual welfare. In her discourses and writings from 1863 onward, she discussed frequently the importance of diet and adequate nutrition.", link: "https://m.egwwritings.org/en/book/384/info", read: "https://m.egwwritings.org/en/book/384", pdf: "https://media4.egwwritings.org/pdf/en_CD.pdf", mp3: "https://media4.egwwritings.org/mp3/384/en_CD.zip"},
    {src: desire_ages, title: "The Desire of Ages", description: "The Desire of Ages (Volume 3 of the Conflict of the Ages series) is Ellen White’s classic on the life of Jesus—the One who stands at the center of all human history. No one else has had such a profound influence on Planet Earth as Jesus Christ. In this book the author does not set forth the events of Jesus’ life in strict chronological order, but she presents Him as the One who can satisfy the deepest yearnings of the human heart.", link: "https://m.egwwritings.org/en/book/130/info", read: "https://m.egwwritings.org/en/book/130", pdf: "https://media4.egwwritings.org/pdf/en_DA.pdf", mp3: "The Desire of Ages (Volume 3 of the Conflict of the Ages series) is Ellen White’s classic on the life of Jesus—the One who stands at the center of all human history. No one else has had such a profound influence on Planet Earth as Jesus Christ. In this book the author does not set forth the events of Jesus’ life in strict chronological order, but she presents Him as the One who can satisfy the deepest yearnings of the human heart."},
    {src: heaven, title: "Heaven", description: "Some of Ellen White’s earliest visions contained bright glimpses of heaven and the earth made new. When she came out of vision, this world seemed dark and lonely compared with the brilliant beauty of the world to come which she had seen so vividly. And she often struggled to find the words to describe what she had been shown in vision.", link: "https://m.egwwritings.org/en/book/36/info", read: "https://m.egwwritings.org/en/book/36", pdf: "https://media4.egwwritings.org/pdf/en_Hvn.pdf", mp3: "https://media4.egwwritings.org/mp3/36/en_Hvn.zip"},
    {src: fundamentals, title: "Fundamentals of Christian Education", description: "Compiled from various other works, these complete and unabridged articles give detailed counsel on the topic of education, while also providing the full context of each statement. From the Biblical method of schooling, to home training, to the work and qualifications of teachers, this publication gives thorough guidance for anyone working with children or in the educational field.", link: "https://m.egwwritings.org/en/book/32/info", read: "https://m.egwwritings.org/en/book/32", pdf: "https://media4.egwwritings.org/pdf/en_FE.pdf", mp3: "https://media4.egwwritings.org/mp3/32/en_FE.zip"},
    {src: patriarchs, title: "Patriarchs and Prophets", description: "Patriarchs and Prophets is the first volume in the Conflict of the Ages series. It covers the sweeping panorama of human history from the creation of Earth to the reign of Israel's King David. With unusual insights the author describes the role of our planet in the cosmic conflict between right and wrong,", link: "https://m.egwwritings.org/en/book/84/info", read: "https://m.egwwritings.org/en/book/84", pdf: "https://media4.egwwritings.org/pdf/en_PP.pdf", mp3: "https://media4.egwwritings.org/mp3/84/en_PP.zip"},
    {src: stewardship, title: "Counsels on Stewardship", description: "Stewardship is properly managing the resources that God has committed to our care. This volume gathers together all of Ellen White's published statements on the subject. Topics discussed include tithing, and being good stewards of the blessings granted unto us by the Lord. This book is a great resource that will help you with the management of those resources and will help you to be good givers.", link: "https://m.egwwritings.org/en/book/22/info", read: "https://m.egwwritings.org/en/book/22", pdf: "https://media4.egwwritings.org/pdf/en_CS.pdf", mp3: "https://media4.egwwritings.org/mp3/22/en_CS.zip"},
]

